### ISSUE TITLE
[iOS] Refactor: 3주차 피드백 내용 반영

### ISSUE THREAD

**Issue by raindropiOS** [masters2023-2nd-project-02/second-hand#222]
# 📝  이슈에 대한 설명
3주차 피드백 내용을 반영합니다.

# 📌 Task Lists
- [ ] : shared 삭제하기 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240622401) 
- [ ] : Result 타입 적용하기 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240625133)
- [x] : decodeJSON 메소드 수정 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240625472)
- [ ] : fetchProductsData 메소드 Result 타입 적용 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240626387)
- [x] : URLRequestFactory 네이밍 변경 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240627666)
- [ ] : ProductRepository, create, add 메소드 수정 및 추가 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240628895) 
- [ ] : ProductRepository, 이니셜라이저 사용하기 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1240629071)
- [x] : URLRequestFactory Helper로 바꾸기 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1241446690)
- [ ] : DTO, CodingKey 적용하기 [🧷](https://github.com/codesquad-members-2023/second-hand/pull/65#discussion_r1241428760)
