### ISSUE TITLE
[FE] Refactor: 미흡한 기능 보완하기  

### ISSUE THREAD

**Issue by hoongding** [masters2023-2nd-project-02/second-hand#287]
# 📝  이슈에 대한 설명
[FE] Refactor: 미흡한 기능 보완하기

# 📌 Task Lists
- [ ] : 상품 판매 페이지 API 모두 붙이기(삭제, 수정)
- [ ] : 동네 설정 삭제, 변경 API 붙이기
- [ ] : 좋아요 누른 상품 하트 색칠되게끔 바꾸기
