### ISSUE TITLE
[FE] Refactor: 1주차 리뷰 반영

### ISSUE THREAD

**Issue by hoongding** [masters2023-2nd-project-02/second-hand#47]
# 📝  이슈에 대한 설명
[FE] Refactor: 1주차 리뷰 반영

# 📌 Task Lists
- [x] : prop-types dependency 제거
- [x] : tsconfig 절대 경로 중복 설정 제거
- [x] : 컴파일 될 필요없는 js 확장자 제거
- [x] : 사장된 `craco-alias`를 `react-app-alias`로 변경
